s01_activity/django_practice/urls.py
from django.urls import path

from . import views

app_name = 'django_practice'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:groceryitem_id>/', views.groceryitem, name='viewgroceryitem'),
	# django_practice/register
	path('register', views.register, name='register'),
	# django_practice/change_password
	path('change_password', views.change_password, name='change_password'),
	# django_practice/login
	path('login', views.login_view, name='login'),
	# django_practice/logout
	path('logout', views.logout_view, name='logout')
]

s01_activity/s01_activity/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

s01_activity/django_practice/models.py
from django.db import models

# Create your models here.
class GroceryItem(models.Model):
	item_name = models.CharField(max_length=50)
	category = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')

s01_activity/django_practice/forms.py
from django import forms


class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=20)

s01_activity/django_practice/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import GroceryItem
from django.contrib.auth.models import User 
from django.contrib.auth import authenticate, login, logout  
from django.forms.models import model_to_dict

# Create your views here.
def index(request):
	groceryitem_list = GroceryItem.objects.all()
	context = {
		'groceryitem_list': groceryitem_list,
		'user': request.user
	}
	return render(request, "django_practice/index.html", context)

def groceryitem(request, groceryitem_id):
	groceryitem = model_to_dict(GroceryItem.objects.get(pk=groceryitem_id))
	return render(request, "django_practice/groceryitem.html", groceryitem)


def register(request):
	users = User.objects.all()
	is_user_registered = False
	context = {
		"is_user_registered": is_user_registered
	}

	for indiv_user in users:
		if indiv_user.username == "johndoe":
			is_user_registered = True
			break

	if is_user_registered == False:
		user = User()	
		user.username = "johndoe"
		user.first_name = "John"
		user.last_name = "Doe"
		user.email = "john@mail.com"
		user.set_password("john1234") #set_password will be hashed (encrypted)
		user.is_staff = False
		user.is_active = True
		user.save()
		context = {
			"first_name": user.first_name,
			"last_name": user.last_name,
		}

	return render(request, "django_practice/register.html", context)

def change_password(request):
	is_user_authenticated = False
	user = authenticate(username="johndoe", password="john1234")
	print(user)
	if user is not None:
		authenticated_user = User.objects.get(username="johndoe")
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True
		context = {
			"is_user_authenticated": is_user_authenticated
		}

	return render(request, "django_practice/change_password.html", context)

def login_view(request):
	username = "johndoe"
	password = "johndoe1"
	user = authenticate(username=username, password=password)
	context = {
		"is_user_authenticated": False
	}
	print(user)
	if user is not None:
		login(request, user)
		return redirect("index")
	else:
		return render(request, "django_practice/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("index")

s01_activity/django_practice/templates/django_practice/add_groceryitem.html
add_groceryitem.html

s01_activity/django_practice/templates/django_practice/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct</p>
{% else %}
	<h1>Password Change Successful!</h1>
	<p>User password has been successfully updated</p>
{% endif %}

s01_activity/django_practice/templates/django_practice/delete_groceryitem.html
delete_groceryitem.html

s01_activity/django_practice/templates/django_practice/groceryitem.html
{% extends 'base.html' %}

{% block title %}Update{% endblock %}

{% block content %}
	<div class="text-center my-3">
		<h1>{{ task_name }}</h1>
		<h3>Description</h3>
		<p>{{ description }}</p>
		<h3>Status</h3>
		<p>{{ status }}</p>
		
		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'django_practice:update_groceryitem' id %}" class="text-light text-decoration-none">Edit Task</a>
		</button>

		<button class="btn btn-danger mx-1 text-decoration-none">
			<a href="{% url 'django_practice:delete_groceryitem' id %}" class="text-light text-decoration-none">Delete Task</a>
		</button>

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'django_practice:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
		</button>
		
	</div>
{% endblock %}

s01_activity/django_practice/templates/django_practice/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if todoitem_list and user.is_anonymous == False %}
        <h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Tasks</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                {% for todoitem in todoitem_list %}
                    <a href="{% url 'django_practice:groceryitem' groceryitem.id %}" class="text-decoration-none">
                        <li class="list-group-item">{{ todoitem.task_name }}</li>
                    </a>
                {% endfor %}
                </ul>
            </div>
        </div>

    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'django_practice:login' %}">here</a></p>

    {% else %}
        <p class="text-center">No tasks have been created</p>
    {% endif %}
{% endblock %}

s01_activity/django_practice/templates/django_practice/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Login</h1>
				{% if error == True %}
					<p class="text-danger">Invalid user credentials, please check your username and password</p>
				{% endif %}
				<form action="{% url 'django_practice:login' %}" method="post">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
					{% csrf_token %}

					<div class="mb-3">
					    <label for="username">Username: </label>
					    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
					</div>

					<div class="mb-3">
					    <label for="password">Password: </label>
					    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Login">
					</div>

				</form>
			</div>
		</div>
	</div>
{% endblock %}

s01_activity/django_practice/templates/django_practice/register.html
{% if is_user_registered == False %}
	<h1>Duplicate User Found</h1>
	<p>A duplicate user has been found, user creation unsuccessful</p>
{% else %}
	<h1>User Successfully Created!</h1>
	<p>The account for {{first_name}} {{last_name}} has been successfully created.</p>
{% endif %}

s01_activity/django_practice/templates/django_practice/update_groceryitem.html
update_groceryitem.html

s01_activity/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} To Do App {% endblock %}</title>
	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
	{% include "navbar.html" %}
	
	{% block content %}
	{% endblock %}
	

	<!-- Bootstrap -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

s01_activity/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">To Do App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="add_task">Add Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logout">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>